### ISSUE TITLE
I am not Able to generate the build of this code

### ISSUE THREAD

**Issue by utkarshkatiyar1** [Xeven777/gemini-chat#3]
![image](https://github.com/Xeven777/gemini-chat/assets/98865912/bebf5ff5-0da1-44e9-b274-e12a9fa0339b)

**Comment by Xeven777** [comment]
Can u be more specific with the problem faced? What error did u face and what commands did u run?

**Comment by utkarshkatiyar1** [comment]
it was running on local perfectly but when i was trying to generate a build of this project it was going to give me above error.

I have tried it by the command: npm run build.

**Comment by Xeven777** [comment]
Oops. But it's running fine in mine. & Also build is perfect in Vercel too. U can send the errors screenshot for understanding
